[[redirects]]
from = "/api/*"
to = "https://api.amcoeur.org/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build]
publish = "apps/backoffice/dist"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; img-src 'self' https://api.amcoeur.org; connect-src 'self' https://api.amcoeur.org https://login.microsoftonline.com https://accounts.google.com https://oauth2.googleapis.com; style-src 'self' 'unsafe-inline'"

