[[redirects]]
from = "/api/*"
to = "https://api.amcoeur.org/toto/:splat"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build]
publish = "apps/client/dist"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; img-src 'self' https://api.amcoeur.org; connect-src 'self' https://api.amcoeur.org;"



