import { EmailPayload, EmailRenderer } from "@amcoeur/email-builder";
import { useEffect, useState } from "react";
import { createPortal } from "react-dom";

import { css } from "../../../styled-system/css";

interface EmailPreviewFrameProps {
  /** The email data structure to render */
  payload: EmailPayload;
  /** Base URL for assets resolution */
  baseUrl: string;
}

/**
 * Component that isolates the email rendering within an iframe using a React Portal.
 * This prevents the email's global styles (<html>, <body>) from conflicting with the backoffice UI.
 */
export const EmailPreviewFrame = ({ payload, baseUrl }: EmailPreviewFrameProps) => {
  const [iframeRef, setIframeRef] = useState<HTMLIFrameElement | null>(null);
  const [mountNode, setMountNode] = useState<HTMLElement | null>(null);

  useEffect(() => {
    if (!iframeRef) return;
    const doc = iframeRef.contentDocument;
    if (!doc) return;

    // We portal into the document element directly to handle the <html> tag generated by react-email
    setMountNode(doc.documentElement);
  }, [iframeRef]);

  return (
    <iframe
      title="Email Preview"
      ref={setIframeRef}
      className={css({
        width: "100%",
        height: "100%",
        border: "none",
        backgroundColor: "white",
      })}
    >
      {mountNode && createPortal(<EmailRenderer payload={payload} baseUrl={baseUrl} />, mountNode)}
    </iframe>
  );
};
